<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <parent>
        <artifactId>apaas-api</artifactId>
        <groupId>org.apaas</groupId>
        <version>1.0.0</version>
    </parent>
    <modelVersion>4.0.0</modelVersion>

    <artifactId>apaas-inner-api</artifactId>
    <name>apaas-inner-api</name>
    <description>对内提供远程调用服务API</description>

    <dependencies>
        <!-- 依赖公共模块 -->
        <dependency>
            <groupId>org.apaas</groupId>
            <artifactId>apaas-core</artifactId>
            <version>1.0.0</version>
        </dependency>
        <!-- 引入Spring Cloud相关依赖 -->
        <dependency>
            <groupId>org.springframework.cloud</groupId>
            <artifactId>spring-cloud-starter-openfeign</artifactId>
        </dependency>
    </dependencies>

</project>