<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
        xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <parent>
        <groupId>org.apaas</groupId>
        <artifactId>apaas-api</artifactId>
        <version>${revision}</version>
    </parent>
    
    <artifactId>apaas-inner-api</artifactId>
    <name>apaas-inner-api</name>
    <description>对内提供远程调用服务API</description>
    
    <dependencies>
        <!-- 依赖公共模块 -->
        <dependency>
            <groupId>org.apaas</groupId>
            <artifactId>apaas-core</artifactId>
        </dependency>
        <!-- 依赖WebFlux -->
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-webflux</artifactId>
        </dependency>
        <!-- 引入ReactiveFeign -->
        <dependency>
            <groupId>com.playtika.reactivefeign</groupId>
            <artifactId>feign-reactor-spring-configuration</artifactId>
        </dependency>
        <dependency>
            <groupId>com.playtika.reactivefeign</groupId>
            <artifactId>feign-reactor-cloud</artifactId>
        </dependency>
        <dependency>
            <groupId>com.playtika.reactivefeign</groupId>
            <artifactId>feign-reactor-webclient</artifactId>
        </dependency>
    </dependencies>
    
</project>
