<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <parent>
        <groupId>org.apaas</groupId>
        <artifactId>apaas</artifactId>
        <version>1.0.0</version>
    </parent>

    <artifactId>apaas-micro</artifactId>
    <packaging>pom</packaging>
    <description>APaaS平台微服务模块</description>

    <modules>
        <module>apaas-system</module>
        <module>apaas-auth</module>
        <module>apaas-monitor</module>
        <module>apaas-flow-engine</module>
        <module>apaas-flow-execution</module>
        <module>apaas-form-engine</module>
        <module>apaas-job</module>
        <module>apaas-integration</module>
        <module>apaas-report</module>
        <module>apaas-design-platform</module>
    </modules>

    <dependencies>
        <!-- 核心模块 -->
        <dependency>
            <groupId>org.apaas</groupId>
            <artifactId>apaas-core</artifactId>
        </dependency>
        <dependency>
            <groupId>org.apaas</groupId>
            <artifactId>apaas-common</artifactId>
        </dependency>

        <!--spring-cloud-commons -->
        <!--<dependency>
            <groupId>org.springframework.cloud</groupId>
            <artifactId>spring-cloud-commons</artifactId>
        </dependency>-->

        <!-- Nacos Service Discovery -->
        <!--<dependency>
            <groupId>com.alibaba.cloud</groupId>
            <artifactId>spring-cloud-starter-alibaba-nacos-discovery</artifactId>
        </dependency>-->

        <!-- Nacos Config -->
        <!--<dependency>
            <groupId>com.alibaba.cloud</groupId>
            <artifactId>spring-cloud-starter-alibaba-nacos-config</artifactId>
        </dependency>-->

        <!-- Spring Cloud LoadBalancer -->
        <!--<dependency>
            <groupId>org.springframework.cloud</groupId>
            <artifactId>spring-cloud-starter-loadbalancer</artifactId>
        </dependency>-->

        <!-- Spring Cloud OpenFeign -->
        <!--<dependency>
            <groupId>org.springframework.cloud</groupId>
            <artifactId>spring-cloud-starter-openfeign</artifactId>
        </dependency>-->

    </dependencies>

    <build>
        <plugins>
            <plugin>
                <groupId>org.springframework.boot</groupId>
                <artifactId>spring-boot-maven-plugin</artifactId>
            </plugin>
        </plugins>
    </build>
</project>