server:
  port: 9500

spring:
  application:
    name: apaas-knowledge

  cloud:
    nacos:  # 单机版本关闭nacos 服务发现和配置管理的能力
      config:
        enabled: false
      discovery:
        enabled: false

  jdbc:
    template:
      fetch-size: -1
      max-rows: 100

  r2dbc:
    url: r2dbc:postgresql://jfast-postgresql:5432/jfast-cloud-knowledge
    username: postgres
    password: Postgresql@9527$
    # 连接池配置 (可选)
    pool:
      max-size: 10
      max-idle-time: 30m
      max-acquire-time: 30s

  # 响应式Redis配置
  data:
    redis:
      host: jfast-redis
      port: 6379
      password: Redis@9527$ # 如果没有密码，可注释或删除
      database: 0
      # 连接池配置 (可选)
      lettuce:
        pool:
          max-active: 16
          max-idle: 8
          min-idle: 0
          max-wait: -1ms

  ai:
    ollama:
      base-url: http://localhost:11434
      chat:
        options:
          model: deepseek-r1:1.5b
          temperature: 0.7
          max-tokens: 4096
      embedding:
        options:
          model: bge-m3:567m
          max-tokens: 4096

knowledge:
  file:
    storage:
      path: text_directory

logging:
  level:
    org.springframework.data.r2dbc: DEBUG
    org.springframework.ai: DEBUG
    org.jfast: DEBUG