<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
        xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <parent>
        <groupId>org.apaas</groupId>
        <artifactId>apaas-micro</artifactId>
        <version>${revision}</version>
    </parent>
    
    <artifactId>apaas-design</artifactId>
    <name>apaas-design</name>
    <description>开发平台服务</description>
    
    <dependencies>
        <!-- 领域模块 -->
        <dependency>
            <groupId>org.apaas</groupId>
            <artifactId>apaas-domain</artifactId>
        </dependency>
        <!-- 引入表单引擎相关依赖 -->
        <dependency>
            <groupId>org.apaas</groupId>
            <artifactId>apaas-form-engine</artifactId>
            <version>${project.version}</version>
        </dependency>
        <!-- 引入流程引擎相关依赖 -->
        <dependency>
            <groupId>org.apaas</groupId>
            <artifactId>apaas-flow-engine</artifactId>
            <version>${project.version}</version>
        </dependency>
        <!-- 引入响应式数据库相关依赖 -->
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-data-r2dbc</artifactId>
        </dependency>
    </dependencies>
</project>
