server:
  port: 8080

spring:
  application:
    name: apaas-report
  r2dbc:
    url: r2dbc:postgresql://localhost:5432/apaas_report
    username: postgres
    password: postgres
  cloud:
    openfeign:
      reactive:
        enabled: true

logging:
  level:
    org.springframework.data.r2dbc: DEBUG
    org.springframework.web.reactive: DEBUG

management:
  endpoints:
    web:
      exposure:
        include: "*"